#!/usr/bin/sh


sudo apt update && sudo apt upgrade && snap refresh && sudo apt autoremove

#install zsh
sudo apt install zsh

sudo apt install curl

#install ohmyzsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

source ~/.zshrc

sudo apt install vim

#install git and set up with github
sudo apt install git
git config --global user.email "bflatt72@gmail.com"
git config --global user.name "bflatt72"
echo | echo | ssh-keygen -t ed25519 -C "bflatt72@gmail.com"
eval "$(ssh-agent -s)"
$ ssh-add ~/.ssh/id_ed25519


#install VScode
sudo apt install software-properties-common apt-transport-https
wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
sudo install -o root -g root -m 644 packages.microsoft.gpg /etc/apt/trusted.gpg.d/
sudo sh -c 'echo "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.gpg] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
sudo apt update
sudo apt install code

sudo snap install discord



